CREATE VIEW IF NOT EXISTS tutor_list_vw
AS
SELECT
	DISTINCT T.TUTOR_ID,
	U.FIRST_NAME || ' ' || U.LAST_NAME AS tutor_name,
	T.BIO ,
	T.WEBSITES,
	(
	SELECT
		GROUP_CONCAT(C1.NAME,
		', ')
	FROM
		COURSES C1
	WHERE
		C1.ID IN (
		SELECT
			T1.COURSE_ID
		FROM
			TUTORS T1
		WHERE
			T1.TUTOR_ID = T.TUTOR_ID)) AS courses,
	GROUP_CONCAT(T.COURSE_ID) AS course_id
FROM
	TUTORS T,
	USERS U,
	COURSES C
WHERE
	U.ID = T.TUTOR_ID
	AND C.ID = T.COURSE_ID;