name: Static workspace
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  build_and_deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application project repository
        uses: actions/checkout@v3
      - name: npm install --omit=dev
        run: npm install --omit=dev
      - name: Deploy project
        uses: platformatic/onestep@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: 96d0d5a2-95be-4bd7-ac79-c4fc1662510c
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_STATIC_WORKSPACE_API_KEY }}
          platformatic_config_path: ./platformatic.db.json
        env:
          DATABASE_URL: sqlite://./db.sqlite
          PLT_SERVER_LOGGER_LEVEL: info
          PORT: 3042
          PLT_SERVER_HOSTNAME: 127.0.0.1
